json.extract! listing,
    :id,
    :host_id,
    :title,
    :description,
    :rate,
    :city,
    :address,
    :location_type,
    :longitude,
    :latitude,
    # :by_lat_long,
    :num_bath,
    :expansion,
    :edition_num,
    :language,
    :min_players,
    :max_players
